FROM node:16-alpine as build-stage

WORKDIR /event-app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build  # Build your React app

# Use a smaller image for serving the static files
FROM nginx:alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80  # Or your frontend port
